// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Exam_System.Data;

#nullable disable

namespace Online_Exam_System.Data.Migrations
{
    [DbContext(typeof(OnlineExamContext))]
    [Migration("20250929210800_SeedExams")]
    partial class SeedExams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Online_Exam_System.Models.Diploma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Doplomas");
                });

            modelBuilder.Entity("Online_Exam_System.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("duration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("156d577a-dba5-46d6-b5c5-1b893b1c1cbe"),
                            CreatedAt = new DateTime(2025, 9, 30, 0, 7, 58, 627, DateTimeKind.Local).AddTicks(4556),
                            EndDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PictureUrl = "https://example.com/exams/csharp.png",
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# Basics Exam",
                            UpdatedAt = new DateTime(2025, 9, 30, 0, 7, 58, 627, DateTimeKind.Local).AddTicks(4558),
                            duration = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f4b02ec3-b504-490c-8064-60b42b359b47"),
                            CreatedAt = new DateTime(2025, 9, 30, 0, 7, 58, 627, DateTimeKind.Local).AddTicks(4569),
                            EndDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PictureUrl = "https://example.com/exams/aspnet.png",
                            StartDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ASP.NET Core Web API Exam",
                            UpdatedAt = new DateTime(2025, 9, 30, 0, 7, 58, 627, DateTimeKind.Local).AddTicks(4571),
                            duration = new TimeSpan(0, 2, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
